# Artificial Neural Network

# Installing Keras
# Enter the following command in a terminal (or anaconda prompt for Windows users): conda install -c conda-forge keras

# Part 1 - Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('titanic/train.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

# Part 3 - Making the predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data_train = pd.read_csv("titanic/train.csv")

In [3]:
data_train.drop(['PassengerId','Name'],axis=1,inplace=True)

In [4]:
data_train.Sex.replace({'male':0,'female':1},inplace=True)

In [5]:
data_train.Age.fillna(data_train.Age.mean(),inplace=True)

In [6]:
data_train.Embarked.replace({np.NaN:'S'},inplace=True)

In [7]:
data_train.drop('Cabin',axis=1,inplace=True)

In [8]:
data_train.drop('Ticket',axis=1,inplace=True)

In [9]:
X = data_train.iloc[:,1:].values
y = data_train.iloc[:, 0].values

In [10]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

labelencoder_embarked = LabelEncoder()
X[:, -1] = labelencoder_embarked.fit_transform(X[:, -1])

In [11]:
onehotencoder = OneHotEncoder(categorical_features = [6])
X = onehotencoder.fit_transform(X).toarray()

In [12]:
X = X[:,1:]

In [13]:

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)



In [14]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 42)


In [43]:

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

In [44]:
X_train[1]

array([-0.30756234,  0.61583843, -0.36936484, -0.73769513, -0.51552625,
       -0.4745452 , -0.47367361, -0.38667072])

In [75]:

# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 8))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])


In [76]:

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)


Epoch 1/100
712/712 [==============================] - 0s 416us/step - loss: 0.6900 - accuracy: 0.6180
Epoch 2/100
712/712 [==============================] - 0s 182us/step - loss: 0.6711 - accuracy: 0.6236
Epoch 3/100
712/712 [==============================] - 0s 193us/step - loss: 0.6204 - accuracy: 0.6236
Epoch 4/100
712/712 [==============================] - 0s 182us/step - loss: 0.5720 - accuracy: 0.6236
Epoch 5/100
712/712 [==============================] - 0s 178us/step - loss: 0.5504 - accuracy: 0.6236
Epoch 6/100
712/712 [==============================] - 0s 187us/step - loss: 0.5409 - accuracy: 0.6236
Epoch 7/100
712/712 [==============================] - 0s 180us/step - loss: 0.5341 - accuracy: 0.6994
Epoch 8/100
712/712 [==============================] - 0s 204us/step - loss: 0.5287 - accuracy: 0.8076
Epoch 9/100
712/712 [==============================] - 0s 186us/step - loss: 0.5232 - accuracy: 0.8132
Epoch 10/100
712/712 [==============================] - 0s 190us/step - l

712/712 [==============================] - 0s 163us/step - loss: 0.4024 - accuracy: 0.8371
Epoch 80/100
712/712 [==============================] - 0s 180us/step - loss: 0.4014 - accuracy: 0.8413
Epoch 81/100
712/712 [==============================] - 0s 190us/step - loss: 0.4019 - accuracy: 0.8385
Epoch 82/100
712/712 [==============================] - 0s 173us/step - loss: 0.4019 - accuracy: 0.8357
Epoch 83/100
712/712 [==============================] - 0s 180us/step - loss: 0.4011 - accuracy: 0.8371
Epoch 84/100
712/712 [==============================] - 0s 212us/step - loss: 0.4013 - accuracy: 0.8385
Epoch 85/100
712/712 [==============================] - 0s 256us/step - loss: 0.4004 - accuracy: 0.8357
Epoch 86/100
712/712 [==============================] - 0s 251us/step - loss: 0.4005 - accuracy: 0.8329
Epoch 87/100
712/712 [==============================] - 0s 217us/step - loss: 0.4003 - accuracy: 0.8357
Epoch 88/100
712/712 [==============================] - 0s 190us/step - loss:

In [77]:
y_pred = classifier.predict(X_test)

In [78]:
y_pred = (y_pred > 0.5)

In [79]:
y_pred

array([[False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [

In [80]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
acc = accuracy_score(y_test,y_pred)

In [81]:
cm

array([[95, 10],
       [21, 53]])

In [82]:
acc

0.8268156424581006

## Test

In [156]:
data_test = pd.read_csv("titanic/test.csv")

In [157]:
data_test.drop(['Name','Ticket','Cabin'],axis=1,inplace=True)

In [158]:
data_test.Sex.replace({'male':0,"female":1},inplace=True)

In [159]:
data_test.Age.fillna(data_train.Age.mean(),inplace=True)
data_test.Embarked.replace({np.NaN:'S'},inplace=True)

In [160]:
data_test.Fare.fillna(data_test.Fare.mean(),inplace=True)

In [161]:
passenger_id = data_test.PassengerId
passenger_id

0       892
1       893
2       894
3       895
4       896
       ... 
413    1305
414    1306
415    1307
416    1308
417    1309
Name: PassengerId, Length: 418, dtype: int64

In [162]:
data_test.drop('PassengerId',axis=1,inplace=True)

In [163]:
X = np.array(data_test)
X[:, -1] = labelencoder_embarked.transform(X[:, -1])

X = onehotencoder.transform(X).toarray()




In [164]:
X = X[:,1:]

In [165]:
# Feature Scaling

X = sc.transform(X)

In [166]:
# Predicting the Test set results
y_test_pred = classifier.predict(X)

In [167]:
y_test_pred

array([[0.06160101],
       [0.5157834 ],
       [0.03989536],
       [0.11204663],
       [0.41164467],
       [0.28817844],
       [0.7302519 ],
       [0.17947373],
       [0.7110786 ],
       [0.12504694],
       [0.08909473],
       [0.3002219 ],
       [0.9718212 ],
       [0.03168371],
       [0.98648524],
       [0.9471481 ],
       [0.05229303],
       [0.31505126],
       [0.4500536 ],
       [0.7990669 ],
       [0.5544352 ],
       [0.4478524 ],
       [0.97753435],
       [0.23700768],
       [0.9528717 ],
       [0.01443729],
       [0.96568096],
       [0.28829616],
       [0.30367634],
       [0.12219673],
       [0.04196244],
       [0.1173338 ],
       [0.36001205],
       [0.34718883],
       [0.4244746 ],
       [0.35127354],
       [0.47593608],
       [0.44783768],
       [0.13285038],
       [0.20174626],
       [0.13852024],
       [0.303289  ],
       [0.03658393],
       [0.92747617],
       [0.98618114],
       [0.12934607],
       [0.36681002],
       [0.079

In [168]:
y_pred_new = (y_test_pred > 0.3)

In [169]:
y_pred_new

array([[False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [

In [103]:
len(y_pred_new)

418

In [170]:
import csv

with open('prediction_new_1.csv', mode='w') as fl:
    
    data_writer = csv.writer(fl, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
    for i in range(len(y_pred_new)):
        data_writer.writerow([passenger_id[i],y_pred_new[i]])
    print("file written")

print("The END")

file written
The END


array([[ 892],
       [ 893],
       [ 894],
       [ 895],
       [ 896],
       [ 897],
       [ 898],
       [ 899],
       [ 900],
       [ 901],
       [ 902],
       [ 903],
       [ 904],
       [ 905],
       [ 906],
       [ 907],
       [ 908],
       [ 909],
       [ 910],
       [ 911],
       [ 912],
       [ 913],
       [ 914],
       [ 915],
       [ 916],
       [ 917],
       [ 918],
       [ 919],
       [ 920],
       [ 921],
       [ 922],
       [ 923],
       [ 924],
       [ 925],
       [ 926],
       [ 927],
       [ 928],
       [ 929],
       [ 930],
       [ 931],
       [ 932],
       [ 933],
       [ 934],
       [ 935],
       [ 936],
       [ 937],
       [ 938],
       [ 939],
       [ 940],
       [ 941],
       [ 942],
       [ 943],
       [ 944],
       [ 945],
       [ 946],
       [ 947],
       [ 948],
       [ 949],
       [ 950],
       [ 951],
       [ 952],
       [ 953],
       [ 954],
       [ 955],
       [ 956],
       [ 957],
       [ 9

In [148]:
output = pd.DataFrame({'PassengerId': [passenger_id], 'Survived': [y_pred_new]},index=[0])

In [149]:
output

PassengerId  \
0  [[892], [893], [894], [895], [896], [897], [89...   

                                            Survived  
0  [[False], [True], [False], [False], [True], [F...

In [141]:
y_pred_new.shape

(418, 1)

In [142]:
passenger_id.shape

(418, 1)

In [143]:
y_pred_new = np.array(y_pred_new)
passenger_id = np.array(passenger_id)

In [146]:
# y_pred_new.shape
passenger_id.shape

(418, 1)

In [135]:
passenger_id = np.array(passenger_id).reshape(418,1)

In [129]:
passenger_id.reshape(-1,1)

array([[ 892],
       [ 893],
       [ 894],
       [ 895],
       [ 896],
       [ 897],
       [ 898],
       [ 899],
       [ 900],
       [ 901],
       [ 902],
       [ 903],
       [ 904],
       [ 905],
       [ 906],
       [ 907],
       [ 908],
       [ 909],
       [ 910],
       [ 911],
       [ 912],
       [ 913],
       [ 914],
       [ 915],
       [ 916],
       [ 917],
       [ 918],
       [ 919],
       [ 920],
       [ 921],
       [ 922],
       [ 923],
       [ 924],
       [ 925],
       [ 926],
       [ 927],
       [ 928],
       [ 929],
       [ 930],
       [ 931],
       [ 932],
       [ 933],
       [ 934],
       [ 935],
       [ 936],
       [ 937],
       [ 938],
       [ 939],
       [ 940],
       [ 941],
       [ 942],
       [ 943],
       [ 944],
       [ 945],
       [ 946],
       [ 947],
       [ 948],
       [ 949],
       [ 950],
       [ 951],
       [ 952],
       [ 953],
       [ 954],
       [ 955],
       [ 956],
       [ 957],
       [ 9

In [136]:
passenger_id.shape

(418, 1)